
DROP EXTENSION IF EXISTS postgis CASCADE;

DROP TABLE IF EXISTS "settings" CASCADE;
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "casbin_rules" CASCADE;
DROP TABLE IF EXISTS "security_logs" CASCADE;
DROP TABLE IF EXISTS "address_locations" CASCADE;
DROP TABLE IF EXISTS "addresses" CASCADE;
DROP TABLE IF EXISTS "menus" CASCADE;
DROP TABLE IF EXISTS "menu_roles" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "permissions" CASCADE;
DROP TABLE IF EXISTS "resources" CASCADE;
DROP TABLE IF EXISTS "user_roles" CASCADE;