// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/rinnguyen1614/rin-echo/internal/core/echo"
	mock "github.com/stretchr/testify/mock"

	model "github.com/rinnguyen1614/rin-echo/internal/core/model"

	query "github.com/rinnguyen1614/rin-echo/internal/core/query"

	request "github.com/rinnguyen1614/rin-echo/internal/system/app/model/request"

	response "github.com/rinnguyen1614/rin-echo/internal/system/app/model/response"

	service "github.com/rinnguyen1614/rin-echo/internal/system/app/service"
)

// RoleService is an autogenerated mock type for the RoleService type
type RoleService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *RoleService) Create(_a0 request.CreateRole) (uint, error) {
	ret := _m.Called(_a0)

	var r0 uint
	if rf, ok := ret.Get(0).(func(request.CreateRole) uint); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(request.CreateRole) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *RoleService) Delete(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *RoleService) Get(id uint) (response.Role, error) {
	ret := _m.Called(id)

	var r0 response.Role
	if rf, ok := ret.Get(0).(func(uint) response.Role); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(response.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: q
func (_m *RoleService) Query(q *query.Query) (*model.QueryResult, error) {
	ret := _m.Called(q)

	var r0 *model.QueryResult
	if rf, ok := ret.Get(0).(func(*query.Query) *model.QueryResult); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.QueryResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*query.Query) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, cmd
func (_m *RoleService) Update(id uint, cmd request.UpdateRole) error {
	ret := _m.Called(id, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, request.UpdateRole) error); ok {
		r0 = rf(id, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithContext provides a mock function with given fields: _a0
func (_m *RoleService) WithContext(_a0 echo.Context) service.RoleService {
	ret := _m.Called(_a0)

	var r0 service.RoleService
	if rf, ok := ret.Get(0).(func(echo.Context) service.RoleService); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.RoleService)
		}
	}

	return r0
}

type mockConstructorTestingTNewRoleService interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoleService creates a new instance of RoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoleService(t mockConstructorTestingTNewRoleService) *RoleService {
	mock := &RoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
