app:
  app_name: systemAplication
  env: development
  max_page_size: 1000
  min_page_size: 10
  encryption: "VjntyW4KhM"
  resources:
    resource: resources/resource.yaml
    menu: resources/menu.yaml

casbin:
  model_path: config/rbac_with_pattern_policy_model.conf
  auto_load: true
  auto_load_internal: 86400

database:
  driver: postgresql
  url: postgresql://root:secret@localhost:15432/rin-echo?sslmode=disable
  batch_size: 1000
  migration_url: file://db/migration
  init_data: false

jwt:
  signing_key: v4EW23stY
  expires_time: 86400
  issuer: "rin-echo"

server:
  host: 0.0.0.0
  port: 8090
